# AI LAB 10
## Name: Zainab fuzail
## Roll No: BSAIM-F24-133

<div class="alert alert-block alert-warning">

<b> Data Load </b>
</div>

import libraries

In [1]:


import pandas as pd

In [2]:
import numpy as np

<div class="alert alert-block alert-warning">

<b> Data gathering</b>
</div>

In [3]:
df = pd.read_csv("cleaned_attendance_data.csv")
df

        School DBN  Enrolled  Present
0                0       172      153
1                0       171      154
2                0       172      158
3                0       173      166
4                0       173      164
...            ...       ...      ...
277148        1582       230      136
277149        1582       226      128
277150        1582       226      130
277151        1582       226      127
277152        1582       216       68

[277153 rows x 3 columns]

<div class="alert alert-block alert-warning">

<b> Data Peprocessing</b>
</div>

In [4]:
df.head()

   School DBN  Enrolled  Present
0           0       172      153
1           0       171      154
2           0       172      158
3           0       173      166
4           0       173      164

In [5]:
df.tail()

        School DBN  Enrolled  Present
277148        1582       230      136
277149        1582       226      128
277150        1582       226      130
277151        1582       226      127
277152        1582       216       68

In [6]:
df.describe()

          School DBN      Enrolled        Present
count  277153.000000  277153.00000  277153.000000
mean      793.313210     596.98617     544.499403
std       457.277298     482.90966     452.970313
min         0.000000       1.00000       1.000000
25%       398.000000     329.00000     291.000000
50%       795.000000     476.00000     430.000000
75%      1190.000000     684.00000     640.000000
max      1582.000000    5955.00000    5847.000000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 277153 entries, 0 to 277152
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   School DBN  277153 non-null  int64
 1   Enrolled    277153 non-null  int64
 2   Present     277153 non-null  int64
dtypes: int64(3)
memory usage: 6.3 MB

In [8]:
df.dtypes

School DBN    int64
Enrolled      int64
Present       int64
dtype: object

In [9]:
df['School DBN'].unique()

array([   0,    1,    2, ..., 1580, 1581, 1582], dtype=int64)

In [10]:
df['Enrolled'].nunique()

3102

In [11]:
df.columns

Index(['School DBN', 'Enrolled', 'Present'], dtype='object')

In [12]:
df.isnull()

        School DBN  Enrolled  Present
0            False     False    False
1            False     False    False
2            False     False    False
3            False     False    False
4            False     False    False
...            ...       ...      ...
277148       False     False    False
277149       False     False    False
277150       False     False    False
277151       False     False    False
277152       False     False    False

[277153 rows x 3 columns]

In [13]:
df.isnull().sum()

School DBN    0
Enrolled      0
Present       0
dtype: int64

In [14]:
print(f" rows {df.shape[0]}")
print(f" column {df.shape[1]}")

 rows 277153
 column 3

In [15]:
# Drop Absent and Released columns if they exist (avoid KeyError)
df = df.drop(["Absent", "Released"], axis=1, errors='ignore')

In [16]:
from sklearn.preprocessing import LabelEncoder

# Safely handle missing column to avoid KeyError
col_name = 'Q1 (5)'
if col_name in df.columns:
	data = pd.DataFrame({col_name: df[col_name].unique()})
else:
	print(f"Column '{col_name}' not found in df. Available columns: {list(df.columns)}")
	data = pd.DataFrame({col_name: []})

data_LE = LabelEncoder()
if not data.empty:
	data_LE.fit(np.ravel(data))
else:
	print(f"Skipping LabelEncoder.fit() because '{col_name}' contains no data.")

Column 'Q1 (5)' not found in df. Available columns: ['School DBN', 'Enrolled', 'Present']
Skipping LabelEncoder.fit() because 'Q1 (5)' contains no data.

In [17]:
from sklearn.preprocessing import LabelEncoder

def convertObjToInt(cols):
    for i in cols:
        if i not in df.columns:
            print(f"Column '{i}' not found in df — skipping.")
            continue
        data = pd.DataFrame({i: df[i].unique()})
        data_LE = LabelEncoder()
        data_LE.fit(np.ravel(data))    # data_LE.fit(data)
        df[i] = data_LE.transform(df[i])
        
columns = ['Q1 (5)', 'Q2 (5)', 'Q3 (5)', 'Q4 (5)', 'Q5 (5)',
       'Q6 (5)', 'Q7 (5)', 'Q8 (5)', 'Q9 (5)', 'Q10 (5)', 'Q11 (5)', 'Q12 (5)',]
convertObjToInt(columns)

Column 'Q1 (5)' not found in df — skipping.
Column 'Q2 (5)' not found in df — skipping.
Column 'Q3 (5)' not found in df — skipping.
Column 'Q4 (5)' not found in df — skipping.
Column 'Q5 (5)' not found in df — skipping.
Column 'Q6 (5)' not found in df — skipping.
Column 'Q7 (5)' not found in df — skipping.
Column 'Q8 (5)' not found in df — skipping.
Column 'Q9 (5)' not found in df — skipping.
Column 'Q10 (5)' not found in df — skipping.
Column 'Q11 (5)' not found in df — skipping.
Column 'Q12 (5)' not found in df — skipping.

In [18]:
from sklearn.preprocessing import LabelEncoder

def convertObjToInt(df, cols):
    encoders = {}
    for col in cols:
        if col in df.columns:
            le = LabelEncoder()
            df[col] = le.fit_transform(df[col])
            encoders[col] = le  # save the encoder for future use
        else:
            print(f"Column '{col}' not found in df — skipping.")
    return df, encoders

# Columns to convert
columns = ['Q1 (5)', 'Q2 (5)','Q3 (5)', 'Q4 (5)', 'Q5 (5)',
       'Q6 (5)', 'Q7 (5)', 'Q8 (5)', 'Q9 (5)', 'Q10 (5)', 'Q11 (5)', 'Q12 (5)',]

# Apply conversion
df, encoders = convertObjToInt(df, columns)

Column 'Q1 (5)' not found in df — skipping.
Column 'Q2 (5)' not found in df — skipping.
Column 'Q3 (5)' not found in df — skipping.
Column 'Q4 (5)' not found in df — skipping.
Column 'Q5 (5)' not found in df — skipping.
Column 'Q6 (5)' not found in df — skipping.
Column 'Q7 (5)' not found in df — skipping.
Column 'Q8 (5)' not found in df — skipping.
Column 'Q9 (5)' not found in df — skipping.
Column 'Q10 (5)' not found in df — skipping.
Column 'Q11 (5)' not found in df — skipping.
Column 'Q12 (5)' not found in df — skipping.

In [19]:
df.dtypes

School DBN    int64
Enrolled      int64
Present       int64
dtype: object

In [20]:
def changeFloatToInt(cols):
    for i in cols:
        if i in df.columns:
            df[i] = df[i].astype('int64')
        else:
            print(f"Column '{i}' not found in df — skipping.")

columns = ['Out of 40']
changeFloatToInt(columns)

Column 'Out of 40' not found in df — skipping.

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 277153 entries, 0 to 277152
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   School DBN  277153 non-null  int64
 1   Enrolled    277153 non-null  int64
 2   Present     277153 non-null  int64
dtypes: int64(3)
memory usage: 6.3 MB

In [22]:
df.head()

   School DBN  Enrolled  Present
0           0       172      153
1           0       171      154
2           0       172      158
3           0       173      166
4           0       173      164

In [23]:
df.to_csv('cleaned_attendance_data.csv', index=False, header=True)

In [24]:
df = pd.read_csv('cleaned_attendance_data.csv')
df

        School DBN  Enrolled  Present
0                0       172      153
1                0       171      154
2                0       172      158
3                0       173      166
4                0       173      164
...            ...       ...      ...
277148        1582       230      136
277149        1582       226      128
277150        1582       226      130
277151        1582       226      127
277152        1582       216       68

[277153 rows x 3 columns]

In [25]:
import pandas as pd
df = pd.read_csv('cleaned_attendance_data.csv')
# df.info()
df.columns

Index(['School DBN', 'Enrolled', 'Present'], dtype='object')

In [26]:
# Safely select target column (avoid KeyError if column missing)
target_col = 'Top 9 (out of 45)'

if target_col in df.columns:
	X = df.drop(target_col, axis=1)
	y = df[target_col]
else:
	print(f"Column '{target_col}' not found. Available columns: {list(df.columns)}")
	# choose a sensible fallback if available
	fallback = 'Present' if 'Present' in df.columns else ('Enrolled' if 'Enrolled' in df.columns else None)
	if fallback:
		print(f"Using '{fallback}' as the target variable instead.")
		X = df.drop(fallback, axis=1)
		y = df[fallback]
	else:
		raise KeyError(f"Target column '{target_col}' not found and no suitable fallback available.")

Column 'Top 9 (out of 45)' not found. Available columns: ['School DBN', 'Enrolled', 'Present']
Using 'Present' as the target variable instead.

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 277153 entries, 0 to 277152
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   School DBN  277153 non-null  int64
 1   Enrolled    277153 non-null  int64
 2   Present     277153 non-null  int64
dtypes: int64(3)
memory usage: 6.3 MB

In [27]:
from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(X,y, test_size=0.2, shuffle=False)

In [42]:
# Example
feature_names = train_X.columns.tolist()
print("Columns used for training:")
print(feature_names)

Columns used for training:
['School DBN', 'Enrolled']

In [28]:
print(train_X.shape, train_y.shape)
print(test_X.shape, test_y.shape)

(221722, 2) (221722,)
(55431, 2) (55431,)

In [44]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

file_path = "cleaned_attendance_data.csv"  
data = pd.read_csv(file_path)


X = data[['School DBN', 'Enrolled']].values
y = data['Present'].values


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


knn_model = KNeighborsRegressor(n_neighbors=3)  


knn_model.fit(X_train, y_train)


y_pred = knn_model.predict(X_test)


rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)  

print("Predictions:", y_pred)
print("RMSE:", rmse)
print("MAE:", mae)
print("R² Score (Accuracy):", r2)

Predictions: [ 225.66666667  196.33333333  494.66666667 ...  388.66666667  389.33333333
 1327.        ]
RMSE: 53.302102509035066
MAE: 19.34287672962782
R² Score (Accuracy): 0.9858116187791921

In [45]:
import pickle

model_file = "knn_model.pkl"
with open(model_file, "wb") as f:
    pickle.dump(knn_model, f)
print(f"Model saved to {model_file}")

Model saved to knn_model.pkl

In [46]:

with open(model_file, "rb") as f:
    loaded_model = pickle.load(f)

In [47]:
# Predict using loaded model
new_data = np.array([[0, 173]])  # School 0, 173 enrolled
prediction = loaded_model.predict(new_data)
print("Predicted Present for new data using loaded model:", prediction[0])

Predicted Present for new data using loaded model: 158.0

In [39]:
df.nunique()

School DBN    1583
Enrolled      3102
Present       3727
dtype: int64